name: Analyze Syntax


# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - '**'
    paths:
      - 'soccer_sdk_utils/**'
      - 'tests/**'
      - 'tasks.py'
      - 'setup.py'
      - '.github/workflows/lint.yml'

  # Allow manually trigger
  workflow_dispatch: {}

jobs:
  Quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python "3.10.8"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install '.[dev]'

      - name: Analyze Syntax
        run: inv lint.yml

      - name: Run Tests
        run: inv coverage

      - name: Report Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}

  Release:
    needs: Quality
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python "3.10.8"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_TOKEN }}
